# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsearchRcpp <- function(dim, pts, r) {
    .Call('_dsearchR_dsearchRcpp', PACKAGE = 'dsearchR', dim, pts, r)
}

rcpp_hello_world <- function() {
    .Call('_dsearchR_rcpp_hello_world', PACKAGE = 'dsearchR')
}

