# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find pairs of points within fixed cutoff
#'
#' @param dim The number of spatial dimensions
#' @param pts A list of coordinate vectors (of length dim).
#' @param r The cutoff distance criteria between points (<=r).
#'
#' @return A list of length 2 vectors.
#' @export
#'
#' @examples
#' pts <- list(c(1,1), c(2,1), c(2,2), c(1,2))
#' pairs <- dsearchRcpp(2, pts, 1.1)
#' @useDynLib dsearchR
#' @importFrom Rcpp evalCpp sourceCpp
dsearchRcpp <- function(dim, pts, r) {
    .Call(`_dsearchR_dsearchRcpp`, dim, pts, r)
}

